# Generated by Django 5.2.4 on 2025-07-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MotoList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=50, verbose_name="Модель мотоцикла"),
                ),
                ("description", models.TextField(verbose_name="Описание мотоцикла")),
            ],
            options={
                "verbose_name": "Мотоцикл",
                "verbose_name_plural": "Мотоциклы",
            },
        ),
    ]
