# Generated by Django 5.2.4 on 2025-07-27 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venicle", "0002_motolist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mileage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mileage", models.PositiveIntegerField(verbose_name="Пробег")),
                (
                    "year",
                    models.PositiveSmallIntegerField(verbose_name="Год регистрации"),
                ),
                (
                    "car",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venicle.carslist",
                    ),
                ),
                (
                    "moto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venicle.motolist",
                    ),
                ),
            ],
            options={
                "verbose_name": "пробег",
                "verbose_name_plural": "пробег",
                "ordering": ("-year",),
            },
        ),
    ]
