# Generated by Django 5.2.4 on 2025-07-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venicle", "0003_mileage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mileage",
            name="car",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mileage",
                to="venicle.carslist",
            ),
        ),
    ]
