# Generated by Django 5.2.4 on 2025-07-28 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("venicle", "0004_alter_mileage_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mileage",
            name="moto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mileage",
                to="venicle.motolist",
            ),
        ),
    ]
