# Generated by Django 5.2.4 on 2025-07-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_avatar_user_city_user_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
