# Generated by Django 5.2.4 on 2025-07-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название курса"),
                ),
                ("description", models.TextField(verbose_name="Описание курса")),
                (
                    "preview",
                    models.ImageField(
                        default="images/materials/courses/photo/default.png",
                        upload_to="images/materials/courses/photo/",
                        verbose_name="Картинка",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название урока"),
                ),
                ("description", models.TextField(verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        default="images/materials/lessons/photo/default.png",
                        upload_to="images/materials/lessons/photo/",
                        verbose_name="Картинка",
                    ),
                ),
                (
                    "link_to_the_video",
                    models.CharField(max_length=255, verbose_name="Ссылка на видео"),
                ),
            ],
        ),
    ]
